-- Bibliothèque générique initiale plomberie/chauffage.
-- Les entrées ne prétendent représenter aucune marque ou référence fabricant :
-- marque, référence, fournisseur et prix restent volontairement NULL.

INSERT INTO "MaterialCategory" ("id", "name", "slug", "position", "updatedAt") VALUES
  ('generic_cat_radiateurs', 'Radiateurs', 'radiateurs', 11, CURRENT_TIMESTAMP),
  ('generic_cat_tuyauterie', 'Tuyauterie', 'tuyauterie', 21, CURRENT_TIMESTAMP),
  ('generic_cat_raccords', 'Raccords', 'raccords', 22, CURRENT_TIMESTAMP),
  ('generic_cat_robinetterie', 'Robinetterie', 'robinetterie', 23, CURRENT_TIMESTAMP),
  ('generic_cat_sanitaire', 'Sanitaire', 'sanitaire', 30, CURRENT_TIMESTAMP),
  ('generic_cat_consommables', 'Consommables', 'consommables', 40, CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO NOTHING;

INSERT INTO "MaterialCatalogItem" (
  "id", "categoryId", "name", "description", "specifications", "tags", "unit",
  "defaultPurchasePriceCents", "defaultSalePriceCents", "supplier", "active", "isFixture", "updatedAt"
) VALUES
  ('generic_radiator_steel_horizontal', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='radiateurs'), 'Radiateur eau chaude acier horizontal', 'Matériel générique à dimensionner selon le chantier.', '{"type":"radiateur","energy":"eau chaude","material":"acier","orientation":"horizontal"}'::jsonb, ARRAY['radiateur','chauffage','acier','horizontal','eau chaude'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_radiator_steel_vertical', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='radiateurs'), 'Radiateur eau chaude acier vertical', 'Matériel générique à dimensionner selon le chantier.', '{"type":"radiateur","energy":"eau chaude","material":"acier","orientation":"vertical"}'::jsonb, ARRAY['radiateur','chauffage','acier','vertical','eau chaude'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_radiator_cast_iron', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='radiateurs'), 'Radiateur eau chaude en fonte', 'Matériel générique à dimensionner selon le chantier.', '{"type":"radiateur","energy":"eau chaude","material":"fonte"}'::jsonb, ARRAY['radiateur','chauffage','fonte','eau chaude'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_radiator_aluminium', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='radiateurs'), 'Radiateur eau chaude en aluminium', 'Matériel générique à dimensionner selon le chantier.', '{"type":"radiateur","energy":"eau chaude","material":"aluminium"}'::jsonb, ARRAY['radiateur','chauffage','aluminium','eau chaude'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_towel_radiator_water', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='radiateurs'), 'Radiateur sèche-serviettes eau chaude', 'Matériel générique à dimensionner selon le chantier.', '{"type":"seche-serviettes","energy":"eau chaude"}'::jsonb, ARRAY['radiateur','seche-serviettes','chauffage','salle de bain'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_towel_radiator_electric', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='radiateurs'), 'Radiateur sèche-serviettes électrique', 'Matériel générique à dimensionner selon le chantier.', '{"type":"seche-serviettes","energy":"electrique"}'::jsonb, ARRAY['radiateur','seche-serviettes','electrique','salle de bain'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_electric_radiator_inertia', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='radiateurs'), 'Radiateur électrique à inertie', 'Puissance et dimensions à préciser.', '{"type":"radiateur","energy":"electrique","technology":"inertie"}'::jsonb, ARRAY['radiateur','electrique','inertie','chauffage'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),

  ('generic_copper_12_14', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='tuyauterie'), 'Tube cuivre 12/14', 'Tube cuivre générique vendu au mètre.', '{"type":"tube","material":"cuivre","diameter":"12/14"}'::jsonb, ARRAY['tube','tuyau','cuivre','12/14','plomberie'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_copper_14_16', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='tuyauterie'), 'Tube cuivre 14/16', 'Tube cuivre générique vendu au mètre.', '{"type":"tube","material":"cuivre","diameter":"14/16"}'::jsonb, ARRAY['tube','tuyau','cuivre','14/16','plomberie'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_copper_16_18', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='tuyauterie'), 'Tube cuivre 16/18', 'Tube cuivre générique vendu au mètre.', '{"type":"tube","material":"cuivre","diameter":"16/18"}'::jsonb, ARRAY['tube','tuyau','cuivre','16/18','plomberie'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_copper_20_22', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='tuyauterie'), 'Tube cuivre 20/22', 'Tube cuivre générique vendu au mètre.', '{"type":"tube","material":"cuivre","diameter":"20/22"}'::jsonb, ARRAY['tube','tuyau','cuivre','20/22','plomberie'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_per_12_16', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='tuyauterie'), 'Tube PER 12/16', 'Tube PER générique vendu au mètre.', '{"type":"tube","material":"PER","diameter":"12/16"}'::jsonb, ARRAY['tube','tuyau','per','12/16','plomberie'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_per_16_20', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='tuyauterie'), 'Tube PER 16/20', 'Tube PER générique vendu au mètre.', '{"type":"tube","material":"PER","diameter":"16/20"}'::jsonb, ARRAY['tube','tuyau','per','16/20','plomberie'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_multilayer_16', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='tuyauterie'), 'Tube multicouche diamètre 16', 'Tube multicouche générique vendu au mètre.', '{"type":"tube","material":"multicouche","diameter":"16 mm"}'::jsonb, ARRAY['tube','tuyau','multicouche','16','plomberie'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_multilayer_20', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='tuyauterie'), 'Tube multicouche diamètre 20', 'Tube multicouche générique vendu au mètre.', '{"type":"tube","material":"multicouche","diameter":"20 mm"}'::jsonb, ARRAY['tube','tuyau','multicouche','20','plomberie'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_multilayer_26', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='tuyauterie'), 'Tube multicouche diamètre 26', 'Tube multicouche générique vendu au mètre.', '{"type":"tube","material":"multicouche","diameter":"26 mm"}'::jsonb, ARRAY['tube','tuyau','multicouche','26','plomberie'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_pvc_32', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='tuyauterie'), 'Tube PVC évacuation diamètre 32', 'Tube PVC générique vendu au mètre.', '{"type":"tube","material":"PVC","diameter":"32 mm","usage":"evacuation"}'::jsonb, ARRAY['tube','tuyau','pvc','32','evacuation'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_pvc_40', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='tuyauterie'), 'Tube PVC évacuation diamètre 40', 'Tube PVC générique vendu au mètre.', '{"type":"tube","material":"PVC","diameter":"40 mm","usage":"evacuation"}'::jsonb, ARRAY['tube','tuyau','pvc','40','evacuation'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_pvc_50', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='tuyauterie'), 'Tube PVC évacuation diamètre 50', 'Tube PVC générique vendu au mètre.', '{"type":"tube","material":"PVC","diameter":"50 mm","usage":"evacuation"}'::jsonb, ARRAY['tube','tuyau','pvc','50','evacuation'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_pvc_100', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='tuyauterie'), 'Tube PVC évacuation diamètre 100', 'Tube PVC générique vendu au mètre.', '{"type":"tube","material":"PVC","diameter":"100 mm","usage":"evacuation"}'::jsonb, ARRAY['tube','tuyau','pvc','100','evacuation'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),

  ('generic_elbow_copper', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='raccords'), 'Coude cuivre à souder', 'Diamètre à sélectionner selon le chantier.', '{"type":"coude","material":"cuivre","connection":"a souder"}'::jsonb, ARRAY['raccord','coude','cuivre','souder'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_tee_copper', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='raccords'), 'Té cuivre à souder', 'Diamètre à sélectionner selon le chantier.', '{"type":"te","material":"cuivre","connection":"a souder"}'::jsonb, ARRAY['raccord','te','cuivre','souder'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_coupling_multilayer', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='raccords'), 'Manchon multicouche à sertir', 'Diamètre à sélectionner selon le chantier.', '{"type":"manchon","material":"multicouche","connection":"a sertir"}'::jsonb, ARRAY['raccord','manchon','multicouche','sertir'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_elbow_pvc', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='raccords'), 'Coude PVC évacuation 87°', 'Diamètre à sélectionner selon le chantier.', '{"type":"coude","material":"PVC","angle":"87 degres"}'::jsonb, ARRAY['raccord','coude','pvc','evacuation'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_tee_pvc', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='raccords'), 'Culotte PVC évacuation 45°', 'Diamètre à sélectionner selon le chantier.', '{"type":"culotte","material":"PVC","angle":"45 degres"}'::jsonb, ARRAY['raccord','culotte','pvc','evacuation'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),

  ('generic_ball_valve', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='robinetterie'), 'Vanne à boisseau sphérique', 'Diamètre et filetage à sélectionner.', '{"type":"vanne","mechanism":"boisseau spherique"}'::jsonb, ARRAY['vanne','robinet','plomberie','chauffage'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_radiator_valve', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='robinetterie'), 'Robinet thermostatique de radiateur', 'Corps et raccord à sélectionner selon le radiateur.', '{"type":"robinet thermostatique","usage":"radiateur"}'::jsonb, ARRAY['robinet','thermostatique','radiateur','chauffage'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_pressure_reducer', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='robinetterie'), 'Réducteur de pression', 'Diamètre et plage de pression à sélectionner.', '{"type":"reducteur de pression"}'::jsonb, ARRAY['reducteur','pression','plomberie','arrivee eau'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_safety_group', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='robinetterie'), 'Groupe de sécurité chauffe-eau', 'Raccordement à confirmer selon l’installation.', '{"type":"groupe de securite","usage":"chauffe-eau"}'::jsonb, ARRAY['groupe securite','chauffe-eau','ballon','plomberie'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),

  ('generic_washbasin_mixer', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='sanitaire'), 'Mitigeur de lavabo', 'Modèle générique, dimensions et finition à sélectionner.', '{"type":"mitigeur","usage":"lavabo"}'::jsonb, ARRAY['mitigeur','robinet','lavabo','sanitaire'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_sink_mixer', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='sanitaire'), 'Mitigeur d’évier', 'Modèle générique, dimensions et finition à sélectionner.', '{"type":"mitigeur","usage":"evier"}'::jsonb, ARRAY['mitigeur','robinet','evier','cuisine'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_toilet_mechanism', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='sanitaire'), 'Mécanisme de chasse d’eau', 'Compatibilité avec le réservoir à confirmer.', '{"type":"mecanisme chasse","usage":"WC"}'::jsonb, ARRAY['wc','toilettes','chasse eau','mecanisme'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_siphon_washbasin', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='sanitaire'), 'Siphon de lavabo', 'Diamètre et encombrement à confirmer.', '{"type":"siphon","usage":"lavabo"}'::jsonb, ARRAY['siphon','lavabo','evacuation','sanitaire'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),

  ('generic_ptfe_tape', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='consommables'), 'Ruban PTFE d’étanchéité', 'Consommable générique pour raccords filetés.', '{"type":"etancheite","material":"PTFE"}'::jsonb, ARRAY['ptfe','teflon','etancheite','raccord'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_sealing_fiber', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='consommables'), 'Filasse et pâte d’étanchéité', 'Consommables génériques pour raccords filetés.', '{"type":"etancheite","material":"filasse"}'::jsonb, ARRAY['filasse','pate','etancheite','raccord'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_pvc_glue', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='consommables'), 'Colle PVC évacuation', 'Colle à sélectionner selon le diamètre et l’usage.', '{"type":"colle","material":"PVC"}'::jsonb, ARRAY['colle','pvc','evacuation','consommable'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
