-- Deuxième lot de matériels génériques plomberie/chauffage.
-- Aucun fabricant, référence, fournisseur ou prix n'est inventé.

INSERT INTO "MaterialCategory" ("id", "name", "slug", "position", "updatedAt") VALUES
  ('generic_cat_chauffe_eau', 'Chauffe-eau', 'chauffe-eau', 12, CURRENT_TIMESTAMP),
  ('generic_cat_generateurs', 'Chaudières et pompes à chaleur', 'generateurs-chauffage', 13, CURRENT_TIMESTAMP),
  ('generic_cat_circulation', 'Circulation et régulation', 'circulation-regulation', 14, CURRENT_TIMESTAMP),
  ('generic_cat_traitement_eau', 'Traitement de l’eau', 'traitement-eau', 24, CURRENT_TIMESTAMP),
  ('generic_cat_evacuation', 'Évacuation', 'evacuation', 25, CURRENT_TIMESTAMP),
  ('generic_cat_gaz', 'Gaz', 'gaz', 26, CURRENT_TIMESTAMP),
  ('generic_cat_ventilation', 'Ventilation', 'ventilation', 31, CURRENT_TIMESTAMP),
  ('generic_cat_isolation_fixation', 'Isolation et fixation', 'isolation-fixation', 41, CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO NOTHING;

INSERT INTO "MaterialCatalogItem" (
  "id", "categoryId", "name", "description", "specifications", "tags", "unit",
  "defaultPurchasePriceCents", "defaultSalePriceCents", "supplier", "active", "isFixture", "updatedAt"
) VALUES
  ('generic_water_heater_50_vertical', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='chauffe-eau'), 'Chauffe-eau électrique vertical 50 L', 'Modèle générique, raccordement et dimensions à confirmer.', '{"type":"chauffe-eau","energy":"electrique","capacity":"50 L","orientation":"vertical"}'::jsonb, ARRAY['chauffe-eau','ballon','cumulus','electrique','50l'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_water_heater_100_vertical', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='chauffe-eau'), 'Chauffe-eau électrique vertical 100 L', 'Modèle générique, raccordement et dimensions à confirmer.', '{"type":"chauffe-eau","energy":"electrique","capacity":"100 L","orientation":"vertical"}'::jsonb, ARRAY['chauffe-eau','ballon','cumulus','electrique','100l'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_water_heater_150_vertical', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='chauffe-eau'), 'Chauffe-eau électrique vertical 150 L', 'Modèle générique, raccordement et dimensions à confirmer.', '{"type":"chauffe-eau","energy":"electrique","capacity":"150 L","orientation":"vertical"}'::jsonb, ARRAY['chauffe-eau','ballon','cumulus','electrique','150l'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_water_heater_200_vertical', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='chauffe-eau'), 'Chauffe-eau électrique vertical 200 L', 'Modèle générique, raccordement et dimensions à confirmer.', '{"type":"chauffe-eau","energy":"electrique","capacity":"200 L","orientation":"vertical"}'::jsonb, ARRAY['chauffe-eau','ballon','cumulus','electrique','200l'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_water_heater_300_stable', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='chauffe-eau'), 'Chauffe-eau électrique stable 300 L', 'Modèle générique, raccordement et dimensions à confirmer.', '{"type":"chauffe-eau","energy":"electrique","capacity":"300 L","orientation":"stable"}'::jsonb, ARRAY['chauffe-eau','ballon','cumulus','electrique','300l','stable'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_water_heater_horizontal', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='chauffe-eau'), 'Chauffe-eau électrique horizontal', 'Capacité, raccordement et dimensions à confirmer.', '{"type":"chauffe-eau","energy":"electrique","orientation":"horizontal"}'::jsonb, ARRAY['chauffe-eau','ballon','cumulus','horizontal'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_thermodynamic_water_heater', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='chauffe-eau'), 'Chauffe-eau thermodynamique', 'Capacité, configuration aéraulique et puissance à confirmer.', '{"type":"chauffe-eau","energy":"thermodynamique"}'::jsonb, ARRAY['chauffe-eau','thermodynamique','ballon','pompe chaleur'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_water_heater_tripod', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='chauffe-eau'), 'Trépied pour chauffe-eau', 'Compatibilité et charge admissible à confirmer.', '{"type":"trepied","usage":"chauffe-eau"}'::jsonb, ARRAY['trepied','chauffe-eau','support','ballon'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),

  ('generic_gas_boiler_wall', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='generateurs-chauffage'), 'Chaudière gaz murale à condensation', 'Puissance, fumisterie et production d’eau chaude à définir.', '{"type":"chaudiere","energy":"gaz","technology":"condensation","installation":"murale"}'::jsonb, ARRAY['chaudiere','gaz','condensation','murale','chauffage'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_gas_boiler_floor', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='generateurs-chauffage'), 'Chaudière gaz au sol à condensation', 'Puissance, fumisterie et production d’eau chaude à définir.', '{"type":"chaudiere","energy":"gaz","technology":"condensation","installation":"sol"}'::jsonb, ARRAY['chaudiere','gaz','condensation','sol','chauffage'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_air_water_heat_pump', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='generateurs-chauffage'), 'Pompe à chaleur air/eau', 'Puissance et configuration hydraulique à dimensionner.', '{"type":"pompe a chaleur","source":"air","distribution":"eau"}'::jsonb, ARRAY['pac','pompe chaleur','air eau','chauffage'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_heat_pump_buffer_tank', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='generateurs-chauffage'), 'Ballon tampon chauffage', 'Volume et raccordements à dimensionner.', '{"type":"ballon tampon","usage":"chauffage"}'::jsonb, ARRAY['ballon tampon','chauffage','pac','chaudiere'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_expansion_vessel_heating', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='generateurs-chauffage'), 'Vase d’expansion chauffage', 'Volume et pression de gonflage à dimensionner.', '{"type":"vase expansion","usage":"chauffage"}'::jsonb, ARRAY['vase expansion','chauffage','chaudiere','pac'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_expansion_vessel_sanitary', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='generateurs-chauffage'), 'Vase d’expansion sanitaire', 'Volume et pression de gonflage à dimensionner.', '{"type":"vase expansion","usage":"sanitaire"}'::jsonb, ARRAY['vase expansion','sanitaire','chauffe-eau'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),

  ('generic_heating_circulator', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='circulation-regulation'), 'Circulateur de chauffage', 'Entraxe, raccordement et hauteur manométrique à confirmer.', '{"type":"circulateur","usage":"chauffage"}'::jsonb, ARRAY['circulateur','pompe','chauffage','chaudiere'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_underfloor_manifold', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='circulation-regulation'), 'Collecteur de plancher chauffant', 'Nombre de départs et raccordements à confirmer.', '{"type":"collecteur","usage":"plancher chauffant"}'::jsonb, ARRAY['collecteur','nourrice','plancher chauffant','chauffage'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_plumbing_manifold', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='circulation-regulation'), 'Collecteur sanitaire', 'Nombre de départs et raccordements à confirmer.', '{"type":"collecteur","usage":"sanitaire"}'::jsonb, ARRAY['collecteur','nourrice','sanitaire','plomberie'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_room_thermostat_wired', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='circulation-regulation'), 'Thermostat d’ambiance filaire', 'Compatibilité avec le générateur à confirmer.', '{"type":"thermostat","connection":"filaire"}'::jsonb, ARRAY['thermostat','filaire','regulation','chauffage'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_room_thermostat_wireless', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='circulation-regulation'), 'Thermostat d’ambiance sans fil', 'Compatibilité avec le générateur à confirmer.', '{"type":"thermostat","connection":"sans fil"}'::jsonb, ARRAY['thermostat','radio','sans fil','regulation','chauffage'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_automatic_air_vent', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='circulation-regulation'), 'Purgeur d’air automatique', 'Filetage et pression de service à confirmer.', '{"type":"purgeur","operation":"automatique"}'::jsonb, ARRAY['purgeur','air','automatique','chauffage'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_sludge_separator', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='circulation-regulation'), 'Pot à boues magnétique', 'Diamètre et débit à confirmer.', '{"type":"pot a boues","technology":"magnetique"}'::jsonb, ARRAY['pot boues','desemboueur','magnetique','chauffage'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_air_separator', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='circulation-regulation'), 'Séparateur d’air chauffage', 'Diamètre et débit à confirmer.', '{"type":"separateur air","usage":"chauffage"}'::jsonb, ARRAY['separateur air','degazeur','chauffage'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),

  ('generic_filter_housing', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='traitement-eau'), 'Porte-filtre pour eau', 'Diamètre, taille et cartouche à sélectionner.', '{"type":"porte-filtre","usage":"eau"}'::jsonb, ARRAY['filtre','porte-filtre','traitement eau','plomberie'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_sediment_cartridge', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='traitement-eau'), 'Cartouche filtrante sédiments', 'Seuil de filtration et dimensions à sélectionner.', '{"type":"cartouche","filtration":"sediments"}'::jsonb, ARRAY['cartouche','filtre','sediments','traitement eau'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_carbon_cartridge', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='traitement-eau'), 'Cartouche filtrante charbon actif', 'Dimensions et capacité à sélectionner.', '{"type":"cartouche","filtration":"charbon actif"}'::jsonb, ARRAY['cartouche','filtre','charbon','traitement eau'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_water_softener', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='traitement-eau'), 'Adoucisseur d’eau', 'Volume de résine et capacité à dimensionner.', '{"type":"adoucisseur"}'::jsonb, ARRAY['adoucisseur','calcaire','traitement eau','resine'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_backflow_preventer', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='traitement-eau'), 'Disconnecteur hydraulique', 'Type, diamètre et zone de protection à confirmer.', '{"type":"disconnecteur"}'::jsonb, ARRAY['disconnecteur','antipollution','reseau eau','plomberie'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_check_valve', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='traitement-eau'), 'Clapet anti-retour', 'Diamètre et type de raccordement à confirmer.', '{"type":"clapet anti-retour"}'::jsonb, ARRAY['clapet','anti-retour','plomberie','pompe'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),

  ('generic_floor_drain', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='evacuation'), 'Siphon de sol', 'Sortie, diamètre et hauteur à confirmer.', '{"type":"siphon","usage":"sol"}'::jsonb, ARRAY['siphon sol','evacuation','douche','sanitaire'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_shower_drain', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='evacuation'), 'Caniveau de douche', 'Longueur, sortie et débit à confirmer.', '{"type":"caniveau","usage":"douche"}'::jsonb, ARRAY['caniveau','douche','evacuation','salle de bain'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_sink_waste', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='evacuation'), 'Vidage d’évier', 'Nombre de cuves et diamètre à confirmer.', '{"type":"vidage","usage":"evier"}'::jsonb, ARRAY['vidage','evier','bonde','evacuation'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_basin_waste', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='evacuation'), 'Bonde de lavabo', 'Avec ou sans trop-plein à confirmer.', '{"type":"bonde","usage":"lavabo"}'::jsonb, ARRAY['bonde','lavabo','vidage','evacuation'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_washing_machine_trap', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='evacuation'), 'Siphon de machine à laver', 'Montage et diamètre d’évacuation à confirmer.', '{"type":"siphon","usage":"machine a laver"}'::jsonb, ARRAY['siphon','machine laver','evacuation','buanderie'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_lift_pump', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='evacuation'), 'Pompe de relevage eaux usées', 'Débit, hauteur et type d’effluent à dimensionner.', '{"type":"pompe relevage","usage":"eaux usees"}'::jsonb, ARRAY['pompe relevage','eaux usees','evacuation'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),

  ('generic_gas_shutoff_valve', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='gaz'), 'Robinet d’arrêt gaz', 'Diamètre, raccordement et conformité à confirmer.', '{"type":"robinet arret","fluid":"gaz"}'::jsonb, ARRAY['gaz','robinet','vanne','arret'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_gas_flexible_hose', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='gaz'), 'Flexible gaz', 'Type de gaz, raccordements et longueur à confirmer.', '{"type":"flexible","fluid":"gaz"}'::jsonb, ARRAY['gaz','flexible','raccordement'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_gas_regulator', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='gaz'), 'Détendeur gaz', 'Gaz, pression et débit à confirmer.', '{"type":"detendeur","fluid":"gaz"}'::jsonb, ARRAY['gaz','detendeur','pression'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_gas_detector', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='gaz'), 'Détecteur de gaz', 'Gaz détecté et alimentation à confirmer.', '{"type":"detecteur","fluid":"gaz"}'::jsonb, ARRAY['gaz','detecteur','securite'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),

  ('generic_vmc_single_flow', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='ventilation'), 'Groupe VMC simple flux', 'Débits, nombre de piquages et commande à confirmer.', '{"type":"VMC","technology":"simple flux"}'::jsonb, ARRAY['vmc','ventilation','simple flux','aeration'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_extract_vent_80', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='ventilation'), 'Bouche d’extraction diamètre 80', 'Débit et pièce de destination à confirmer.', '{"type":"bouche extraction","diameter":"80 mm"}'::jsonb, ARRAY['vmc','bouche','extraction','80','ventilation'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_extract_vent_125', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='ventilation'), 'Bouche d’extraction diamètre 125', 'Débit et pièce de destination à confirmer.', '{"type":"bouche extraction","diameter":"125 mm"}'::jsonb, ARRAY['vmc','bouche','extraction','125','ventilation'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_duct_80', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='ventilation'), 'Gaine de ventilation diamètre 80', 'Nature et isolation de la gaine à confirmer.', '{"type":"gaine","diameter":"80 mm","usage":"ventilation"}'::jsonb, ARRAY['gaine','vmc','ventilation','80'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_duct_125', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='ventilation'), 'Gaine de ventilation diamètre 125', 'Nature et isolation de la gaine à confirmer.', '{"type":"gaine","diameter":"125 mm","usage":"ventilation"}'::jsonb, ARRAY['gaine','vmc','ventilation','125'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_condensate_pump', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='ventilation'), 'Pompe de relevage de condensats', 'Débit et hauteur de relevage à confirmer.', '{"type":"pompe condensats"}'::jsonb, ARRAY['pompe','condensats','climatisation','chaudiere'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),

  ('generic_pipe_insulation_16', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='isolation-fixation'), 'Manchon isolant pour tube diamètre 16', 'Épaisseur et classe d’isolation à confirmer.', '{"type":"isolant tube","diameter":"16 mm"}'::jsonb, ARRAY['isolant','manchon','tube','16','calorifuge'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_pipe_insulation_22', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='isolation-fixation'), 'Manchon isolant pour tube diamètre 22', 'Épaisseur et classe d’isolation à confirmer.', '{"type":"isolant tube","diameter":"22 mm"}'::jsonb, ARRAY['isolant','manchon','tube','22','calorifuge'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_pipe_clip_single', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='isolation-fixation'), 'Collier de fixation simple pour tube', 'Diamètre et support à confirmer.', '{"type":"collier","mount":"simple"}'::jsonb, ARRAY['collier','fixation','tube','plomberie'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_pipe_clip_double', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='isolation-fixation'), 'Collier de fixation double pour tube', 'Diamètre et support à confirmer.', '{"type":"collier","mount":"double"}'::jsonb, ARRAY['collier','fixation','tube','plomberie'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_threaded_rod', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='isolation-fixation'), 'Tige filetée de fixation', 'Diamètre et longueur à confirmer.', '{"type":"tige filetee"}'::jsonb, ARRAY['tige filetee','fixation','support'], 'm', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP),
  ('generic_sanitary_silicone', (SELECT "id" FROM "MaterialCategory" WHERE "slug"='isolation-fixation'), 'Mastic silicone sanitaire', 'Couleur et conditionnement à sélectionner.', '{"type":"mastic","material":"silicone","usage":"sanitaire"}'::jsonb, ARRAY['silicone','mastic','joint','sanitaire','etancheite'], 'u', NULL, NULL, NULL, true, false, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
