"use client";
import { useRouter } from "next/navigation";
import { type FormEvent, useState } from "react";
import { MARKETPLACE_TRADES } from "@/src/lib/marketplace";

type Requirement={tradeKey:string;customTradeName:string|null;requiredCount:number;startDate:string;endDate:string};
type InitialPosting={id:string;title:string;trade:string;trades:string[];description:string;location:string;startDate:string;endDate:string;positions:number;budgetCents:number|null;requirements:Requirement[]};

export default function MarketplacePostingForm({initialPosting}:{initialPosting?:InitialPosting}){
 const router=useRouter(); const [pending,setPending]=useState(false); const [error,setError]=useState("");
 const [startDate,setStartDate]=useState(initialPosting?.startDate??""); const [endDate,setEndDate]=useState(initialPosting?.endDate??"");
 const [requirements,setRequirements]=useState<Requirement[]>(initialPosting?.requirements.length?initialPosting.requirements:[]);
 const update=(key:string,changes:Partial<Requirement>)=>setRequirements((all)=>all.map((item)=>item.tradeKey===key?{...item,...changes}:item));
 function toggle(label:string){const key=label==="Autre"?"OTHER":label;setRequirements((all)=>all.some((item)=>item.tradeKey===key)?all.filter((item)=>item.tradeKey!==key):[...all,{tradeKey:key,customTradeName:null,requiredCount:1,startDate,endDate}]);}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(pending)return;if(!requirements.length)return setError("Sélectionne au moins un métier recherché.");if(requirements.some((item)=>!item.startDate||!item.endDate||(item.tradeKey==="OTHER"&&!item.customTradeName?.trim())))return setError("Complète chaque besoin, notamment le métier personnalisé et sa période.");setPending(true);setError("");const formData=new FormData(event.currentTarget);const body={...Object.fromEntries(formData),startDate,endDate,requirements};const response=await fetch(initialPosting?`/api/marketplace/${initialPosting.id}`:"/api/marketplace",{method:initialPosting?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));setPending(false);if(!response.ok)return setError(typeof data.error==="string"?data.error:"Impossible d’enregistrer l’annonce.");router.push(`/marketplace/${initialPosting?.id??data.posting.id}`);router.refresh();}
 return <form onSubmit={submit} className="forge-surface mt-6 grid gap-4 rounded-3xl border p-5 sm:grid-cols-2 sm:p-7">
  <label className="text-sm font-semibold sm:col-span-2">Titre<input required name="title" maxLength={140} defaultValue={initialPosting?.title??""} placeholder="Rénovation d’un appartement" className="mt-1.5 min-h-12 w-full rounded-xl border bg-transparent px-3 font-normal"/></label>
  <label className="text-sm font-semibold">Ville / zone<input required name="location" maxLength={120} defaultValue={initialPosting?.location??""} placeholder="Saint-Denis" className="mt-1.5 min-h-12 w-full rounded-xl border bg-transparent px-3 font-normal"/></label>
  <label className="text-sm font-semibold">Budget facultatif (€)<input name="budget" type="number" min="0" step="0.01" defaultValue={initialPosting?.budgetCents==null?"":initialPosting.budgetCents/100} className="mt-1.5 min-h-12 w-full rounded-xl border bg-transparent px-3 font-normal"/></label>
  <fieldset className="grid gap-3 rounded-2xl border p-4 sm:col-span-2 sm:grid-cols-2"><legend className="px-2 text-sm font-bold">Période du chantier</legend><label className="text-sm font-semibold">Début<input required type="date" value={startDate} onChange={(e)=>setStartDate(e.target.value)} className="mt-1.5 min-h-12 w-full rounded-xl border bg-transparent px-3 font-normal"/></label><label className="text-sm font-semibold">Fin<input required type="date" value={endDate} onChange={(e)=>setEndDate(e.target.value)} className="mt-1.5 min-h-12 w-full rounded-xl border bg-transparent px-3 font-normal"/></label></fieldset>
  <fieldset className="sm:col-span-2"><legend className="text-sm font-bold uppercase tracking-wide">Métiers recherchés</legend><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-3">{MARKETPLACE_TRADES.map((label)=>{const key=label==="Autre"?"OTHER":label;const checked=requirements.some((item)=>item.tradeKey===key);return <label key={label} className={`flex min-h-11 items-center gap-2 rounded-xl border px-3 text-sm ${checked?"border-blue-400 bg-blue-50 text-blue-700 dark:bg-blue-950 dark:text-blue-300":""}`}><input type="checkbox" checked={checked} onChange={()=>toggle(label)}/><span>{label}</span></label>})}</div></fieldset>
  {requirements.length?<section className="space-y-3 sm:col-span-2"><h2 className="text-sm font-bold uppercase tracking-wide">Besoins par métier</h2>{requirements.map((item)=>{const label=item.tradeKey==="OTHER"?item.customTradeName||"Autre":item.tradeKey;return <article key={item.tradeKey} className="rounded-2xl border p-4"><h3 className="font-bold text-blue-700 dark:text-blue-300">{label}</h3>{item.tradeKey==="OTHER"?<label className="mt-3 block text-sm font-semibold">Précisez le métier<input required value={item.customTradeName??""} onChange={(e)=>update(item.tradeKey,{customTradeName:e.target.value})} maxLength={80} placeholder="Étancheur" className="mt-1.5 min-h-11 w-full rounded-xl border bg-transparent px-3 font-normal"/></label>:null}<div className="mt-3 grid gap-3 sm:grid-cols-3"><div><p className="text-sm font-semibold">Nombre recherché</p><div className="mt-1.5 grid grid-cols-[2.75rem_1fr_2.75rem] overflow-hidden rounded-xl border"><button type="button" onClick={()=>update(item.tradeKey,{requiredCount:Math.max(1,item.requiredCount-1)})} className="min-h-11 border-r text-lg">−</button><span className="grid place-items-center font-bold">{item.requiredCount}</span><button type="button" onClick={()=>update(item.tradeKey,{requiredCount:Math.min(20,item.requiredCount+1)})} className="min-h-11 border-l text-lg">+</button></div></div><label className="text-sm font-semibold">Besoin du<input required type="date" min={startDate} max={endDate} value={item.startDate} onChange={(e)=>update(item.tradeKey,{startDate:e.target.value})} className="mt-1.5 min-h-11 w-full rounded-xl border bg-transparent px-2 font-normal"/></label><label className="text-sm font-semibold">Au<input required type="date" min={startDate} max={endDate} value={item.endDate} onChange={(e)=>update(item.tradeKey,{endDate:e.target.value})} className="mt-1.5 min-h-11 w-full rounded-xl border bg-transparent px-2 font-normal"/></label></div></article>})}</section>:null}
  <label className="text-sm font-semibold sm:col-span-2">Description publique<textarea required name="description" maxLength={2000} defaultValue={initialPosting?.description??""} placeholder="Décris brièvement le chantier et les renforts recherchés." className="mt-1.5 min-h-32 w-full rounded-xl border bg-transparent p-3 font-normal"/></label>
  {error?<p className="text-sm font-medium text-red-600 dark:text-red-400 sm:col-span-2">{error}</p>:null}<div className="grid grid-cols-2 gap-3 sm:col-span-2"><button type="button" onClick={()=>router.back()} className="min-h-12 rounded-xl border font-semibold">Annuler</button><button disabled={pending} className="min-h-12 rounded-xl bg-blue-600 font-semibold text-white disabled:opacity-60">{pending?"Enregistrement…":initialPosting?"Enregistrer":"Publier"}</button></div>
 </form>;
}
