"use client";
import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";

type Supplier = { id: string; name: string; companyName: string | null; phone: string | null; email: string | null; active: boolean };
export default function SupplierManager({ initialSuppliers, canWrite }: { initialSuppliers: Supplier[]; canWrite: boolean }) {
  const [suppliers, setSuppliers] = useState(initialSuppliers); const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const visible = useMemo(() => { const q = search.trim().toLocaleLowerCase("fr"); return q ? suppliers.filter((supplier) => `${supplier.name} ${supplier.companyName ?? ""}`.toLocaleLowerCase("fr").includes(q)) : suppliers; }, [search, suppliers]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const body = Object.fromEntries(new FormData(form)); const response = await fetch("/api/suppliers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) return setError(data.error ?? "Enregistrement impossible."); setSuppliers((current) => [...current, data.supplier].sort((a,b)=>a.name.localeCompare(b.name,"fr"))); setOpen(false); form.reset(); }
  return <section className="mt-6"><div className="flex gap-3"><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Rechercher un fournisseur…" className="min-h-12 min-w-0 flex-1 rounded-2xl border border-[var(--forge-border)] bg-[var(--forge-surface)] px-4"/>{canWrite && <button onClick={()=>setOpen(true)} className="rounded-2xl bg-blue-600 px-4 font-semibold text-white">Ajouter</button>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2">{visible.map((supplier)=><Link key={supplier.id} href={`/settings/suppliers/${supplier.id}`} className={`forge-surface rounded-2xl border p-4 ${supplier.active ? "" : "opacity-55"}`}><h2 className="font-bold text-[var(--forge-text-primary)]">{supplier.name}</h2>{supplier.companyName && <p className="text-sm text-[var(--forge-text-secondary)]">{supplier.companyName}</p>}<p className="mt-2 text-sm text-[var(--forge-text-muted)]">{[supplier.phone,supplier.email].filter(Boolean).join(" · ") || "Coordonnées à compléter"}</p></Link>)}</div>{!visible.length && <p className="py-12 text-center text-[var(--forge-text-muted)]">Aucun fournisseur pour l’instant.</p>}{open && <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/20 p-3 backdrop-blur-[3px]"><form onSubmit={submit} className="forge-surface max-h-[calc(100dvh-6rem-env(safe-area-inset-bottom))] w-full max-w-lg overflow-y-auto rounded-3xl border p-5"><h2 className="text-xl font-bold">Ajouter un fournisseur</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required name="name" placeholder="Nom *" className="min-h-11 rounded-xl border bg-transparent px-3"/><input name="companyName" placeholder="Société" className="min-h-11 rounded-xl border bg-transparent px-3"/><input name="phone" placeholder="Téléphone" className="min-h-11 rounded-xl border bg-transparent px-3"/><input name="email" type="email" placeholder="E-mail" className="min-h-11 rounded-xl border bg-transparent px-3"/><input name="address" placeholder="Adresse" className="min-h-11 rounded-xl border bg-transparent px-3 sm:col-span-2"/><input name="website" placeholder="Site internet" className="min-h-11 rounded-xl border bg-transparent px-3"/><input name="accountReference" placeholder="N° de compte client" className="min-h-11 rounded-xl border bg-transparent px-3"/><textarea name="notes" placeholder="Notes" className="rounded-xl border bg-transparent p-3 sm:col-span-2"/></div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<div className="sticky bottom-0 mt-5 grid grid-cols-2 gap-3 bg-[var(--forge-surface)] pt-3"><button type="button" onClick={()=>setOpen(false)} className="min-h-12 rounded-xl border font-semibold">Annuler</button><button className="min-h-12 rounded-xl bg-blue-600 font-semibold text-white">Ajouter</button></div></form></div>}</section>;
}
